### PR TITLE
added a list and mapped over it

### PR DESCRIPTION
**Pull request by Alli12324**

### CODE REVIEW

**Comment by BrandonKiefer** [comment]
Your assignment is nearly complete but there's one little issue. Your React code is in the wrong file. Your src folder has 2 files: App.js and App.jsx

In React, we render elements to the DOM of our root element in our index using JSX. If you try to run your app the way it currently is, all you will see is the default React and Vite logos.

Replace the code in your JSX file with the code from your App.js file and then run the app to see the difference. You can delete the App.js file when you're done.

Once you've done this, please resubmit your assignment right away so that it can be marked as complete. Apologies for the late review on your assignment-- you are going to be assigned to a new mentor who will be reviewing your assignments. If your assignments aren't reviewed after 4 days, please contact your CIL Jason or myself.

**Comment by BrandonKiefer** [comment]
Hi Allison, your JSX file still has the default Vite and React template. What do you see when you run your React app? For the mapped array list to appear on the page when you run the app, you will need that code in your JSX file.

**Comment by justiceotuya** [comment]
Hi Allison, you seem to have deleted the wrong `App.js` file. you deleted the file with your work and only the default App.js file can be seen so I can't see your work. 

This is how you would fix it 

- go to this link https://github.com/Alli12324/react-todo/blob/12ca1953aab6af5be2a673111fe4109561fe461a/src/App.js and you will see your deleted file (you can see it because git stores the history of your commit)
- copy the code from that file
- paste it into your current `App.jsx` file replacing the current code there.
- run it and ensure you can see your new todo list
- the push to GitHub and send a merge request

contact me on the slack group if you are finding it difficult

**Comment by Alli12324** [comment]
> Hi Allison, your JSX file still has the default Vite and React template. What do you see when you run your React app? For the mapped array list to appear on the page when you run the app, you will need that code in your JSX file.



> Hi Allison, you seem to have deleted the wrong `App.js` file. you deleted the file with your work and only the default App.js file can be seen so I can't see your work.
> 
> This is how you would fix it
> 
> * go to this link https://github.com/Alli12324/react-todo/blob/12ca1953aab6af5be2a673111fe4109561fe461a/src/App.js and you will see your deleted file (you can see it because git stores the history of your commit)
> * copy the code from that file
> * paste it into your current `App.jsx` file replacing the current code there.
> * run it and ensure you can see your new todo list
> * the push to GitHub and send a merge request
> 
> contact me on the slack group if you are finding it difficult

Hi Thank you for your feedback, I was having trouble viewing the app on my browser so I did not realize that I did not save my changes properly. I am now seeing my Todo list when I run the app. Please let me know if everything looks ok, Thank you!

**Review by justiceotuya — APPROVED** [review]

**Pull request merged**
